import IndisputableMonolith

#eval IndisputableMonolith.URCAdapters.routeA_end_to_end_demo
#eval IndisputableMonolith.URCAdapters.routeB_closure_report  
#eval IndisputableMonolith.URCAdapters.lambda_report
#eval IndisputableMonolith.URCAdapters.grand_manifest
